jwt:
  access-token:
    expiry: 3600
    secret-key: '*&t8&TBD98OTN#*O7DTO7*#TB87#TBS*Q&TQ#D(S*B@O*&D(&@^F#'

  refresh-token:
    expiry: 86400
    secret-key: '*&t8&TBD98OTN#*O7DTO7*#TB8D#&D@#^B&D#@^(7#TBS*Q&TQ#D(S*B@O*&D(&@^F#'

spring:
  application:
    name: social-network-app

  datasource:
    password: 7410
    url: jdbc:postgresql://localhost:5432/social_network
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <GOOGLE_CLIENT_ID>
            client-secret: <GOOGLE_CLIENT_SECRET>

  mail:
    host: smtp.gmail.com
    port: 587
    username: farkhod.go@gmail.com
    password: <APP_PASSWORD>

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

email:
  code-validity: 120

file:
  base-path: uploads/